version: '2'
services:
  nodejs:
    container_name: nodejs
    image: node:19-alpine
    volumes:
      - ./:/app:rw
    command: |
      - /bin/bash
      - -c
      - |
        cd /app
        npm install
